# Generated by Django 4.0.2 on 2022-05-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_is_serviceprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_serviceprovider',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
