# Generated by Django 4.0.2 on 2022-05-28 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twinregister', '0005_alter_verticlemilling_coolant_aas_and_more'),
        ('TwinServices', '0004_alter_notificationservice_serviceprovider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationservice',
            name='twin_selected',
        ),
        migrations.AddField(
            model_name='notificationservice',
            name='twin_selected',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='twinregister.verticlemilling'),
        ),
    ]
