# Generated by Django 4.0.2 on 2022-06-01 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TwinServices', '0007_serviceprovider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='serviceprovider',
            field=models.ForeignKey(limit_choices_to={'is_serviceprovider': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
