# Generated by Django 4.0.2 on 2022-06-01 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TwinServices', '0008_alter_serviceprovider_serviceprovider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='serviceprovider',
            new_name='serviceproviders',
        ),
    ]
