# Generated by Django 4.0.2 on 2022-06-01 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TwinServices', '0009_rename_serviceprovider_serviceproviders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationservice',
            name='services',
        ),
        migrations.AddField(
            model_name='notificationservice',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TwinServices.services_outsourced'),
        ),
    ]
