# Generated by Django 4.0.2 on 2022-06-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TwinServices', '0010_remove_notificationservice_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationservice',
            name='services',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
