# Generated by Django 4.0.2 on 2022-03-24 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticleMilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twin_id', models.CharField(max_length=15)),
                ('display_name', models.CharField(max_length=20)),
                ('ip_address', models.CharField(max_length=20)),
                ('port_number', models.IntegerField(max_length=7)),
                ('is_connected', models.BooleanField(default=False)),
                ('floor_id', models.IntegerField(max_length=7)),
                ('tool_aas', models.CharField(max_length=200)),
                ('spindle_aas', models.CharField(max_length=200)),
                ('coolant_aas', models.CharField(max_length=200)),
                ('emergency_on', models.BooleanField(default=False)),
                ('power_on', models.BooleanField(default=False)),
                ('is_loaded', models.BooleanField(default=False)),
                ('cycle_on', models.BooleanField(default=False)),
                ('maxtravel_X', models.CharField(max_length=20)),
                ('maxtravel_Y', models.CharField(max_length=20)),
                ('maxtravel_Z', models.CharField(max_length=20)),
                ('programfile_link', models.CharField(max_length=200)),
                ('wcsoffset_X', models.CharField(max_length=20)),
                ('wcsoffset_Y', models.CharField(max_length=20)),
                ('wcsoffset_Z', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
