# Generated by Django 4.0.2 on 2022-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verticlemilling',
            name='floor_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='verticlemilling',
            name='port_number',
            field=models.IntegerField(),
        ),
    ]
