# Generated by Django 4.0.2 on 2022-03-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinregister', '0003_verticlemilling_otherdetails_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verticlemilling',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='verticlemilling',
            name='programfile_link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
