# Generated by Django 4.0.2 on 2022-04-14 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twinregister', '0004_alter_verticlemilling_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verticlemilling',
            name='coolant_aas',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='verticlemilling',
            name='otherdetails_link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='verticlemilling',
            name='spindle_aas',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='verticlemilling',
            name='tool_aas',
            field=models.URLField(),
        ),
    ]
